### ISSUE TITLE
File perm 400 on userkey.pem is too restrictive

### ISSUE THREAD

**Issue by valerytschopp** [italiangrid/voms-clients#1]
I tried to voms proxy init with the new client, but it will not read userkey.pem (perm 600)!!!

$ voms-proxy-init -voms aec       
Credentials couldn't be loaded [/Users/tschopp/.globus/userkey.pem, /Users/tschopp/.globus/usercert.pem]: Wrong file permissions on file /Users/tschopp/.globus/userkey.pem. Required permissions are: 400
No credentials found!
$ :(

Enforcing a file perm of 400 is a bit too much, as 600 is also perfectly acceptable...

**Comment by andreaceccanti** [comment]
This fix has been provided some time ago.
Closing it.

Thanks
