### ISSUE TITLE
Build without RPM

### ISSUE THREAD

**Issue by jtchilders** [italiangrid/voms-clients#15]
We would like to use voms clients to create proxies on non-RPM systems where we do not have root access. Your README does not indicate if this is possible. Otherwise, could you provide instructions for building voms-proxy-init/info without RPM support?

**Comment by andreaceccanti** [comment]
The voms-clients build process, documented in the README, produces a tarball, you're not forced to use RPMs. See:
https://github.com/italiangrid/voms-clients/blob/master/README.md#build
