### ISSUE TITLE
Build Failure on non-LHC grid system

### ISSUE THREAD

**Issue by jtchilders** [italiangrid/voms-clients#16]
Hello,
I'm trying to build voms-proxy-init/info on a non-SLC system using maven 3.3 with java 1.8.0_51. 
When I run mvn package I get the errors below. I'm not a Java programmer and have never used Maven so I could use some help understanding the errors. I'm building on the Edison supercomputer login nodes at NERSC in the US where we hope to run ATLAS production jobs. Obviously this is not an LHC Grid environment.
Thanks.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.322 s
[INFO] Finished at: 2017-02-22T07:04:47-08:00
[INFO] Final Memory: 34M/2319M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project voms-clients: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /global/u1/p/parton/panda/voms-clients/src/main/java/org/italiangrid/voms/clients/ProxyDestroyBehaviour.java:30: warning: no description for @param
[ERROR] * @param params
[ERROR] ^
[ERROR] /global/u1/p/parton/panda/voms-clients/src/main/java/org/italiangrid/voms/clients/impl/DefaultProxyDestroyBehaviour.java:42: warning: no description for @param
[ERROR] * @param listener
[ERROR] ^
[ERROR] /global/u1/p/parton/panda/voms-clients/src/main/java/org/italiangrid/voms/clients/impl/ProxyDestroyListenerAdapter.java:35: warning: no @param for proxyFile
[ERROR] public void warnProxyToRemove(String proxyFile);
[ERROR] ^
[ERROR] /global/u1/p/parton/panda/voms-clients/src/main/java/org/italiangrid/voms/clients/strategies/ProxyInfoStrategy.java:24: error: invalid use of @param
[ERROR] * @param options
[ERROR] ^
[ERROR] /global/u1/p/parton/panda/voms-clients/src/main/java/org/italiangrid/voms/clients/util/VersionProvider.java:39: warning: no description for @param
[ERROR] * @param command
[ERROR] ^
[ERROR]
[ERROR] Command line was: /opt/java/jdk1.8.0_51/jre/../bin/javadoc @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in '/global/u1/p/parton/panda/voms-clients/target/javadoc' dir.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by andreaceccanti** [comment]
Hi,

please update your repo to get the latest changes for the master branch and try the build again, I've just merged some changes that should fix your build problem.

**Comment by andreaceccanti** [comment]
@jtchilders Did the suggestion above solve your build issue?

**Comment by jtchilders** [comment]
Hi Andrea,
This did solve the problem. Thanks!
Taylor


J. Taylor Childers
Argonne National Laboratory
High Energy Physics Division
Building 360, Room C-217
Office: +1 (630) 252-4212
Mobile: +1 (331) 302-4647

**Comment by andreaceccanti** [comment]
great, so I close this issue.

Thanks,
