### ISSUE TITLE
stack overwrite in voms-client 2 series

### ISSUE THREAD

**Issue by smithdh** [italiangrid/voms-clients#8]
Hi,

I've seen there is this issue with voms-client 2.0.11:

https://jira.opensciencegrid.org/browse/SOFTWARE-1333

i.e. the version in the EMI3 repo: 

http://emisoft.web.cern.ch/emisoft/dist/EMI/3/sl6/x86_64/updates/voms-clients-2.0.11-1.el6.x86_64.rpm has this problem. I believe this was part of the April 2014 update:

http://www.eu-emi.eu/releases/emi-3-monte-bianco/updates/-/asset_publisher/5Na8/content/update-10-04-11-2013-v-3-6-0-1#VOMS_clients_v_3_0_4_VOMS_Java_A

although I've seen the build date of the RPM was October 2013. Will there be a fix in the voms-client 2 series, is it still being updated ?

Thanks,
David

**Comment by andreaceccanti** [comment]
The v2 clients that fixed this issue were released some time ago:

http://italiangrid.github.io/voms/2014/10/24/several-voms-releases.html

Closing this.

Thanks
